---

- name: Remove a Tenant using AS3
  hosts: all
  connection: local

  vars:
    provider:
      password: admin
      server: 10.1.1.245
      user: admin
      validate_certs: no
      server_port: 443
      timeout: 60

  tasks:
    - name: Remove tenant from AS3 configurations
      bigip_appsvcs_extension:
        tenants:
        - ACME_cloud_ANSIBLE
        state: absent
        provider: "{{ provider }}"
      delegate_to: localhost
